config/routes.rb
Rails.application.routes.draw do
  root to: 'public_pages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :sessions
  namespace :admin do
    root to: 'homes#index'
    resources :users
    resources :categories
    resources :products
    resources :orders
  end
  get '/auth/google_oauth2', as: 'google'
  get 'auth/:provider/callback', to: 'sessions#login_google'
  get 'auth/failure', to: redirect('/')
  resources :account_activations, only: [:edit]
end

app/views/layouts/modules/_category.html.slim
li.
  = link_to category.name, category_path(category.id)

app/views/layouts/modules/_chat_room.html.slim
#ChatModal.modal.fade.bs-example-modal-lg[tabindex="-1" role="dialog" aria-labelledby="myModalLabel"]
  .modal-dialog.modal-md[role="document"]
    .modal-content
      .modal-body
        ul.nav.nav-tabs
          li.active
            a[data-toggle="tab" href="#chat_member"]
              = t(".chat_all")
          li
            a[data-toggle="tab" href="#chat_admin"]
              = t(".chat-admin")
        .tab-content.tab-chat
          #chat_member.tab-pane.fade.in.active
            .chat_window
              .top_menu
                .buttons.pull-right
                  .button.close[type="button" data-dismiss="modal"]
                    = content_tag(:i, nil, class: "fa fa-times")
                .title
                  = t(".chat_all")
              ul.messages.member
                .message_template.member
              .bottom_wrapper.clearfix
                .message_input_wrapper
                  input.message_input.member[placeholder="Nhập nội dùng tin nhắn ..."]
                .send_message.member
                  .icon
                  .text
                    = t(".send")
          #chat_admin.tab-pane.fade.in[user-id=""]
            .chat_window
              .top_menu
                .buttons.pull-right
                  .button.close[type="button" data-dismiss="modal"]
                    = content_tag(:i, nil, class: "fa fa-times")
                .title
                  = t(".chat_admin")
              ul.messages.admin
                .message_template.admin
              .bottom_wrapper.clearfix
                .message_input_wrapper
                  input.message_input.admin[placeholder="Nhập nội dùng tin nhắn ..."]
                .send_message.admin
                  .icon
                  .text
                    = t(".send")

script#data-chat-member[type="x-tmpl-mustache"]
  li.message
    .avatar
      img.no-avatar[src="{{IMAGE}}"]
    .text_wrapper
      .text
        | {{MESSAGE}}
      .text_details
        span
          | {{DATETIME}}
      span.name
        | {{NAME}}

script#data-chat-admin[type="x-tmpl-mustache"]
  li.message
    .avatar
      img.no-avatar[src="{{IMAGE}}"]
    .text_wrapper
      .text
        | {{MESSAGE}}
      .text_details
        span
          | {{DATETIME}}
      span.name
        | {{NAME}}

app/views/layouts/modules/_footer.html.slim
.container-fluid
  .container
    hr
    footer.footer
      | Design : Team Ruby Asiantech
    a#back-to-top.btn.btn-primary.btn-lg.back-to-top[href="#" role="button" title="Nhấp để trở lại trên đầu trang" data-toggle="tooltip" data-placement="left"]
      span.glyphicon.glyphicon-chevron-up
div.button-chat[data-toggle="modal" data-target="#ChatModal" data-toggle-tooltip="tooltip" data-placement="left" title="Nhấp vào để chat"]
  div.border-cm-nt
    i.fa.fa-comments.fa-2x
    span.notify-admin
      span.notify-admin-text
        | #{@notifys.size}

= render 'layouts/modules/chat_room'

app/views/layouts/modules/_header.html.slim
nav#main-Nav.navbar.navbar-default.navbar-top[role="navigation"]
  .container
    .row
      .navbar-header
        span#grouped-one.visible-xs.pull-left[onclick="openNav()"]
          | ☰
        span#grouped-two.visible-xs.pull-right

      #main-mav-top.collapse.navbar-collapse
        ul.nav.navbar-nav
          li
            = link_to content_tag(:b, nil, class: "glyphicon glyphicon-home") + " Trang chủ", root_url, :id => "mlinkhome"
        ul.nav.navbar-nav.pull-right
          li.dropdown
            a.dropdown-toggle[data-toggle="dropdown"]
              span.glyphicon.glyphicon-shopping-cart
                span.badge
                  = "0"
              = "Giỏ hàng"
            ul#cartview.dropdown-menu

          - if logged_in?
            
            li.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-expanded="false"]
                span
                  = "Welcome #{current_user.name}"
                span.caret
              ul.dropdown-menu[role="menu"]
                - if true
                  li
                    = link_to "Trang quản trị", "#"
                li
                  = link_to "Thông tin cá nhân", "#"
                li
                  = link_to content_tag(:i, " Đăng xuất", class: "fa fa-btn fa-sign-out"), logout_path, method: :delete
          - else
            li
              = link_to "Đăng nhập"
#mySidenav.sidenav
  a.closebtn[href="javascript:void(0)" onclick="closeNav()"]
    | ×
    = t ".close"
  a[href="#"]
    = t ".phone"
  a[href="#"]
    = t ".laptop"
  a[href="#"]
    = t ".pc"
  a[href="#"]
    span.glyphicon.glyphicon-shopping-cart
      span.badge
    = t ".cart"

app/views/layouts/modules/_introduce.html.slim
.col-xs-12.col-sm-12.col-md-12.col-lg-12
  hr
  .col-xs-12.col-sm-8.col-md-8.col-lg-8.no-padding
    .row.gioithieu
      .col-xs-12.col-sm-4.col-md-4.col-lg-4
        a[href="" title=""]
          strong
            = "GIỚI THIỆU CÔNG TY"
        li
          a[href="#" title=""]
            = "Chính sách mua trả góp"
        li
          a[href="#" title=""]
            = "Câu hỏi thường gặp"
        li
          a[href="#" title=""]
            = "Hệ thống bảo hành"
      .col-xs-12.col-sm-4.col-md-4.col-lg-4
        a[href="" title=""]
          strong
            = "TUYỂN DỤNG"
        li
          a[href="#" title=""]
            = "Tuyển dụng mới nhất"
        li
          a[href="#" title=""]
            = "Hưỡng dẫn mua hàng Online"
        li
          a[href="#" title=""]
            = "Chính sách mua trả góp"
      .col-xs-12.col-sm-4.col-md-4.col-lg-4
        a[href="" title=""]
          strong
            = "HỆ THỐNG CỬA HÀNG"
        li
          a[href="#" title=""]
            = "Kiểm tra hàng chính hãng"
        li
          a[href="#" title=""]
            = "Máy đổi trả"
        li
          a[href="#" title=""]
            = "Hệ thống cửa hàng"
  .col-xs-12.col-sm-4.col-md-4.col-lg-4
    p
      = "Hỗ trợ thanh toán "
      = link_to image_tag("pay.png", alt: ""), "#"
    .gt-left.pull-left
      p
        small
          = "Tư vẫn miễn phí (24/7)"
      strong
        = "1800 xxxx"
    .gt-right.pull-right
      p
        small
          = "Góp ý, phản ánh(8h00 - 22h00)"
      strong
        = "1800 xxxx"

app/views/layouts/modules/_modal_auth.html.slim
- unless logged_in?
  #AuthModal.modal.fade.bs-example-modal-lg[tabindex="-1" role="dialog" aria-labelledby="myModalLabel"]
    .modal-dialog.modal-sm[role="document"]
      .modal-content
        .modal-header
          h4#myModalLabel.modal-title
            ul.nav.nav-tabs
              li.active
                a[data-toggle="tab" href="#login"]
                  | Đăng nhập
              li
                a[data-toggle="tab" href="#register"]
                  | Đăng ký
              li.nopassword
                a[data-toggle="tab" href="#nopassword"]
        .modal-body
          .tab-content
            #login.tab-pane.fade.in.active
              = render 'sessions/new'
            #register.tab-pane.fade
              = render 'users/new'
            #nopassword.tab-pane.fade
              = render 'password_resets/new'
        .modal-footer
          button.btn.btn-primary.pull-left[type="button"]
            i.fa.fa-facebook.pr-1
            |  Facebook
          = link_to content_tag(:i, " Google +", class: "fa fa-google-plus pr-1"), google_path, class: "btn btn-danger pull-right"