config/routes.rb
Rails.application.routes.draw do
  root to: 'public_pages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :sessions
  namespace :admin do
    root to: 'homes#index'
    resources :users
    resources :categories
    resources :products
    resources :orders
  end
  get '/auth/google_oauth2', as: 'google'
  get 'auth/:provider/callback', to: 'sessions#login_google'
  get 'auth/failure', to: redirect('/')
  resources :account_activations, only: [:edit]
end

app/models/order.rb
class Order < ApplicationRecord
  acts_as_paranoid
  PHONE_REGEX = /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/

  has_many :line_items, dependent: :destroy
  belongs_to :user

  enum status: %i[cart notdefined defined cancel]
  enum type_payment: %i[default online]

  default_scope -> { order(created_at: :desc) }
  scope :search_name, ->(search) { where 'name iLIKE ?', "%#{search}%" }
  scope :search_price, ->(min, max) { where 'total_price BETWEEN ? AND ?', min, max }
  scope :search_day, ->(minday, maxday) { where 'created_at BETWEEN ? AND ?', minday, maxday }
  scope :search_status, ->(status) { where 'status = ?', status }
  scope :search_type_payment, ->(type_payment) { where 'type_payment = ?', type_payment }
  scope :not_cart, -> { where.not status: :cart }
  scope :cart, -> { where status: :cart }
end

app/controllers/admin/orders_controller.rb
require 'timers/timer_data'

class Admin::OrdersController < ApplicationAdminController
  include OrdersHelper
  before_action :logged_in_user
  before_action :check_admin
  before_action :load_order_id, only: %i[approve reject]

  def index
    if params[:search].blank?
      @orders = Order.not_cart.paginate(page: params[:page], per_page: 5)
    else
      @orders = Order.all
      search_name
      search_price
      search_day
      search_status
      search_type_payment
      @orders = @orders.not_cart.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
    @line_item = LineItem.by_order_id params[:id]
    respond_to do |format|
      format.json do
        render json: @line_item.as_json(
          only: %i[id amount],
          include: [
            { product: { only: %i[id images name quantity] } },
            { order: { only: %i[id status] } }
          ]
        )
      end
    end
  end

  def approve
    @order.update_attribute :status, :defined
    render json: true
  end

  def reject
    @line_item = @order.line_items.all
    @line_item.each do |key|
      product = Product.find_by id: key.product_id
      product.update_attribute(:quantity, product.quantity + 1)
      TimerData.add_quantity(product.id)
    end
    @order.update_attribute :status, :cancel
    render json: true
  end

  private

    def load_order_id
      @order = Order.find_by id: params[:id]
      @order || render(file: 'public/404.html', status: 404, layout: true)
    end

    def search_name
      if params[:search][:name].present?
        @orders = @orders.joins(:user).search_name params[:search][:name]
      end
    end

    def search_price
      if params[:search][:min].present? && params[:search][:max].present?
        min = add_price params[:search][:min]
        max = add_price params[:search][:max]
        @orders = @orders.search_price min, max
      end
    end

    def search_day
      if params[:search][:minday].present? && params[:search][:maxday].present?
        minday = params[:search][:minday]
        maxday = params[:search][:maxday]
        @orders = @orders.search_day minday, maxday
      end
    end

    def search_status
      return unless params[:search][:status].present?
      status = params[:search][:status]
      @orders = if status == 'notdefined'
                  @orders.search_status 1
                elsif status == 'defined'
                  @orders.search_status 2
                elsif status == 'cancel'
                  @orders.search_status 3
                end
    end

    def search_type_payment
      return unless params[:search][:type_payment].present?
      status = params[:search][:type_payment]
      @orders = if status == 'default'
                  @orders.search_type_payment 0
                elsif status == 'online'
                  @orders.search_type_payment 1
                end
    end
end

app/controllers/orders_controller.rb
require 'timers/timer_data'

class OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_order, only: %i[edit update]
  before_action :correct_line_item, only: %i[destroy]
  before_action :total_price, only: %i[index edit update]

  def index; end

  def edit
    @info = User.find(current_user.id).orders.not_cart.pluck(:user_name, :address, :phone).uniq
    @info_order = Order.find_by(user_id: current_user.id)
  end

  def update
    if update_status
      redirect_to root_path, flash: { success: 'Đặt hàng thành công' }
    else
      render 'edit', flash: { danger: 'Vui lòng xem lại thông tin!' }
    end
  end

  def update_status
    @order.update_attributes(order_params)
    @order.update_attributes(status: 1, total_price: @total_price + 29000)
  end

  def destroy
    product = @line_item.product
    if @line_item.destroy
      product.update_attribute(:quantity, product.quantity + 1)
      TimerData.add_quantity(product.id)
      redirect_to orders_path, flash: { success: 'Xóa sản phẩm thành công!' }
    else
      redirect_to orders_path, flash: { danger: 'Xóa sản phẩm thất bại!' }
    end
  end

  private

    def order_params
      params.require(:order).permit(:user_name, :phone, :address, :type_payment)
    end

    def correct_order
      @order = Order.find_by(user_id: current_user.id)
      unless @order.status == 'cart'
        redirect_to root_path, flash: { danger: 'Đơn hàng đang được xử lý !' }
      end
    end

    def correct_line_item
      @line_item = LineItem.find_by id: params[:id]
    end

    def total_price
      @total_price = 0
      @orders = Order.cart.find_by(user_id: current_user.id)
      if @orders
        @line_items = @orders.line_items
        @line_items.each { |item| @total_price += item.amount }
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def set_mindate
    if params[:search].present?
      params[:search][:minday] if params[:search][:minday].present?
    end
  end

  def set_maxdate
    if params[:search].present?
      params[:search][:maxday] if params[:search][:maxday].present?
    end
  end

  def set_minprice
    if params[:search].present?
      params[:search][:min] if params[:search][:min].present?
    end
  end

  def set_maxprice
    if params[:search].present?
      params[:search][:max] if params[:search][:max].present?
    end
  end

  def set_status
    if params[:search].present?
      params[:search][:status] if params[:search][:status].present?
    end
  end

  def set_type_payment
    if params[:search].present?
      params[:search][:type_payment] if params[:search][:type_payment].present?
    end
  end

  def set_name
    if params[:search].present?
      params[:search][:name] if params[:search][:name].present?
    end
  end
end

app/views/orders/shared/_info_payment.html.slim
.information_payment
  h4
    | Địa chỉ của bạn
  - @info.each_with_index do |info, index|
    .info_billing
      = radio_button_tag 'info', index, checked: true
      span.info_address
        .info_item_name
          = info[0]
        .info_item_phone
          = info[2]
        .info_item_address
          = info[1]
      span.edit_info
        | Chỉnh sửa
  .form_info_payment
    h4
      | Thêm địa chỉ mới
    .form_info_item.label_return
      = button_tag("Chọn địa chỉ đã có", type: "button", class: "btn btn-primary btn-sm return_info")
    .form_info_item.label_name
      label
        | Họ tên
      = text_field_tag(:user_name, nil, class: "form-control", placeholder: "Nhập họ tên")
      p.has_error_order.error_name
    .form_info_item.label_email
      label
        | Email
      = email_field_tag(:email, current_user.email, disabled: true, class: "form-control", placeholder: "Nhập địa email")
    .form_info_item.label_address
      label
        | Địa chỉ
      = text_field_tag(:address, nil, { id: "advanced-placepicker", class: "form-control", placeholder: "Nhập địa chỉ" })
      p.has_error_order.error_address
      #collapseTwo.collapse
        .another-map-class.thumbnail
    .form_info_item.label_phone
      label
        | Số điện thoại
      = telephone_field_tag(:phone, nil, class: "form-control", placeholder: "Nhập số điện thoại")
      p.has_error_order.error_phone
  .add_new_info_billing
    = button_tag("Thêm địa chỉ mới", type: "button", class: "btn btn-info new_billing")
    = button_tag(type: "button", class: "btn btn-warning next-order-1") do
      = content_tag(:i," Tiếp theo", class: "fa fa-shopping-cart")

app/views/orders/shared/_payment_type.html.slim
.payment_type_information
  h4
    | Hình thức giao hàng
  .delivery_type
    = radio_button_tag 'type-delivery', 'default', checked: true
    span.info_delivery
      .delivery-item.deliver_first
        | Giao hàng tiêu chuẩn - giao hàng tận nơi.
      .delivery-item
        | giao hàng 1-3 ngày | từ 29.000 ₫
      .delivery-item
        = content_tag(:i, nil, class: "fa fa-money" ) + "  "
        = content_tag(:i, nil, class: "fa fa-university")
  .payment_type
    h4
      | Hình thức thanh toán
    ul
      = hidden_field_tag(:type_payment, value: :default)
      li.payment-item.payment-live
        div.payment-title
          = t(".cash-on-delivery")
        div
          i.fa.fa-money.fa-3x.payment-center
        .form-check
          label
            = check_box_tag :type, "default", nil, class: "cbb_offline"
            = content_tag(:span, nil, class: "label-text")
      li.payment-item.payment-onl
        div.payment-title
          = t(".atm-bank-transfer")
        div
          i.fa.fa-university.fa-3x.payment-center
        .form-check
          label
            = check_box_tag :type, "online", nil, class: "cbb_online"
            = content_tag(:span, nil, class: "label-text")
  div.pay-info.pay-live-info
    p.pay-info-item.pay-live
      = t(".stander-delivery")
      br
      = t(".cash-delivery")
      br
      = t(".order-24h")
      br
      = t(".next-to-confirm")
  div.bank-payment
    h3.title-bank
      = t(".select-your-bank")
    div.bank-item.nganluong
      img[src="https://www.nganluong.vn/css/newhome/img/button/safe-pay-3.png" border="0"]
  br
  = button_tag(type: "button", class: "btn btn-warning next-order-3") do 
   =content_tag(:i," Tiếp theo", class: "fa fa-shopping-cart")
  

app/views/orders/shared/_progress_bar.html.slim
ul.nav.nav-tabs.payment_progress_bar
  li.active
    a[data-toggle="tab" href="#info_payment"]
      | Thông tin thanh toán
  li
    a[data-toggle="tab" href="#type_payment"]
      | Hình thức thanh toán
  li.disabled
    a[data-toggle="tab" href="#summary_order"]
      | Tình trạng đơn hàng
.tab-content.tab-auction
  #info_payment.tab-pane.fade.in.active
    = render 'orders/shared/info_payment'
  #type_payment.tab-pane.fade
    = render 'orders/shared/payment_type'
  #summary_order.tab-pane.fade
    = render 'orders/shared/summary_payment'

app/views/orders/shared/_summary_payment.html.slim
  = form_for @order, url: order_path(@order.id), html: { id: "formOrder", class: "form-horizontal", :method => :patch } do |f|
    .form_order_hidden
      .control-group
        = f.text_field :user_name
      .control-group
        = f.email_field :email, { value: current_user.email }
      .control-group
        = f.text_field :address
      .control-group
        = f.telephone_field :phone
      .control-group
        = f.text_field :type_payment
      span.sum_pay
        = @total_price + 29000
      span.order_id
        = @order.id
    .sum_info
      h4
        | Thông tin giao hàng
      .sum_info_item.sum_name
        label
          | Họ tên
        span.sum_name_o
      .sum_info_item.address
        label
          | Địa chỉ giao hàng
        span.sum_address_o
      .sum_info_item.phone
        label
          | Số điện thoại
        span.sum_phone_o
    .sum_type_payment
      h4
        | Hình thức thanh toán
      .sum_info_item
        label
          | Kiểu thanh toán
        span.type_payment_o

    = button_tag(type: "submit", class: "btn btn-warning btn-lg btn-pay") do
      = content_tag(:i, "Đặt hàng", class: "fa fa-shopping-cart")

    = button_tag(type: "button", class: "btn btn-warning btn-lg btn-pay-online") do
      = content_tag(:i, "Đặt hàng", class: "fa fa-shopping-cart")