config/routes.rb
Rails.application.routes.draw do
  root to: 'public_pages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :sessions
  namespace :admin do
    root to: 'homes#index'
    resources :users
    resources :categories
    resources :products
    resources :orders
  end
  get '/auth/google_oauth2', as: 'google'
  get 'auth/:provider/callback', to: 'sessions#login_google'
  get 'auth/failure', to: redirect('/')
  resources :account_activations, only: [:edit]
end

app/models/order.rb
class Order < ApplicationRecord
  acts_as_paranoid
  PHONE_REGEX = /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/

  has_many :line_items, dependent: :destroy
  belongs_to :user

  enum status: %i[cart notdefined defined cancel]
  enum type_payment: %i[default online]

  default_scope -> { order(created_at: :desc) }
  scope :search_name, ->(search) { where 'name iLIKE ?', "%#{search}%" }
  scope :search_price, ->(min, max) { where 'total_price BETWEEN ? AND ?', min, max }
  scope :search_day, ->(minday, maxday) { where 'created_at BETWEEN ? AND ?', minday, maxday }
  scope :search_status, ->(status) { where 'status = ?', status }
  scope :search_type_payment, ->(type_payment) { where 'type_payment = ?', type_payment }
  scope :not_cart, -> { where.not status: :cart }
  scope :cart, -> { where status: :cart }
end

app/controllers/admin/orders_controller.rb
require 'timers/timer_data'

class Admin::OrdersController < ApplicationAdminController
  include OrdersHelper
  before_action :logged_in_user
  before_action :check_admin
  before_action :load_order_id, only: %i[approve reject]

  def index
    if params[:search].blank?
      @orders = Order.not_cart.paginate(page: params[:page], per_page: 5)
    else
      @orders = Order.all
      search_name
      search_price
      search_day
      search_status
      search_type_payment
      @orders = @orders.not_cart.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
    @line_item = LineItem.by_order_id params[:id]
    respond_to do |format|
      format.json do
        render json: @line_item.as_json(
          only: %i[id amount],
          include: [
            { product: { only: %i[id images name quantity] } },
            { order: { only: %i[id status] } }
          ]
        )
      end
    end
  end

  def approve
    @order.update_attribute :status, :defined
    render json: true
  end

  def reject
    @line_item = @order.line_items.all
    @line_item.each do |key|
      product = Product.find_by id: key.product_id
      product.update_attribute(:quantity, product.quantity + 1)
      TimerData.add_quantity(product.id)
    end
    @order.update_attribute :status, :cancel
    render json: true
  end

  private

    def load_order_id
      @order = Order.find_by id: params[:id]
      @order || render(file: 'public/404.html', status: 404, layout: true)
    end

    def search_name
      if params[:search][:name].present?
        @orders = @orders.joins(:user).search_name params[:search][:name]
      end
    end

    def search_price
      if params[:search][:min].present? && params[:search][:max].present?
        min = add_price params[:search][:min]
        max = add_price params[:search][:max]
        @orders = @orders.search_price min, max
      end
    end

    def search_day
      if params[:search][:minday].present? && params[:search][:maxday].present?
        minday = params[:search][:minday]
        maxday = params[:search][:maxday]
        @orders = @orders.search_day minday, maxday
      end
    end

    def search_status
      return unless params[:search][:status].present?
      status = params[:search][:status]
      @orders = if status == 'notdefined'
                  @orders.search_status 1
                elsif status == 'defined'
                  @orders.search_status 2
                elsif status == 'cancel'
                  @orders.search_status 3
                end
    end

    def search_type_payment
      return unless params[:search][:type_payment].present?
      status = params[:search][:type_payment]
      @orders = if status == 'default'
                  @orders.search_type_payment 0
                elsif status == 'online'
                  @orders.search_type_payment 1
                end
    end
end

app/controllers/orders_controller.rb
require 'timers/timer_data'

class OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_order, only: %i[edit update]
  before_action :correct_line_item, only: %i[destroy]
  before_action :total_price, only: %i[index edit update]

  def index; end

  def edit
    @info = User.find(current_user.id).orders.not_cart.pluck(:user_name, :address, :phone).uniq
    @info_order = Order.find_by(user_id: current_user.id)
  end

  def update
    if update_status
      redirect_to root_path, flash: { success: 'Đặt hàng thành công' }
    else
      render 'edit', flash: { danger: 'Vui lòng xem lại thông tin!' }
    end
  end

  def update_status
    @order.update_attributes(order_params)
    @order.update_attributes(status: 1, total_price: @total_price + 29000)
  end

  def destroy
    product = @line_item.product
    if @line_item.destroy
      product.update_attribute(:quantity, product.quantity + 1)
      TimerData.add_quantity(product.id)
      redirect_to orders_path, flash: { success: 'Xóa sản phẩm thành công!' }
    else
      redirect_to orders_path, flash: { danger: 'Xóa sản phẩm thất bại!' }
    end
  end

  private

    def order_params
      params.require(:order).permit(:user_name, :phone, :address, :type_payment)
    end

    def correct_order
      @order = Order.find_by(user_id: current_user.id)
      unless @order.status == 'cart'
        redirect_to root_path, flash: { danger: 'Đơn hàng đang được xử lý !' }
      end
    end

    def correct_line_item
      @line_item = LineItem.find_by id: params[:id]
    end

    def total_price
      @total_price = 0
      @orders = Order.cart.find_by(user_id: current_user.id)
      if @orders
        @line_items = @orders.line_items
        @line_items.each { |item| @total_price += item.amount }
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def set_mindate
    if params[:search].present?
      params[:search][:minday] if params[:search][:minday].present?
    end
  end

  def set_maxdate
    if params[:search].present?
      params[:search][:maxday] if params[:search][:maxday].present?
    end
  end

  def set_minprice
    if params[:search].present?
      params[:search][:min] if params[:search][:min].present?
    end
  end

  def set_maxprice
    if params[:search].present?
      params[:search][:max] if params[:search][:max].present?
    end
  end

  def set_status
    if params[:search].present?
      params[:search][:status] if params[:search][:status].present?
    end
  end

  def set_type_payment
    if params[:search].present?
      params[:search][:type_payment] if params[:search][:type_payment].present?
    end
  end

  def set_name
    if params[:search].present?
      params[:search][:name] if params[:search][:name].present?
    end
  end
end

app/views/admin/orders/index.html.erb
<%= javascript_include_tag "admin/order/order_details" %>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
  <div class="row">
    <ol class="breadcrumb">
      <li>
        <a href="#"><i class="fa fa-home"></i></a>
      </li>
      <li class="active">Danh Sách Đơn Đặt Hàng</li>
    </ol>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-heading">
        <div class="col-lg-3" >
          Danh Sách Đơn Đặt Hàng
        </div>
        <%= form_for :search, url: admin_orders_path, method: :get do |f| %>
          <%= render partial: "admin/orders/shared/search", locals: {f: f} %>
        <% end %>
      </div>
      <br><br>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Tên khách hàng</th>
                  <th>Địa chỉ</th>
                  <th>Điện thoại</th>
                  <th>Email</th>
                  <th>Ngày đặt</th>
                  <th>Thành tiền</th>
                  <th>Trạng thái</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "admin/orders/shared/listtable", collection: @orders, as: "list" %>
              </tbody>
            </table>
            <%= render "admin/orders/shared/modal" %>
            <%= will_paginate %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "lib/simple.money.format" %>

app/views/admin/orders/index.html.slim
- provide :title, t(".title")
= javascript_include_tag "include/admin/line_item"
.col-sm-9.col-sm-offset-3.col-lg-10.col-lg-offset-2.main
  .row
    ol.breadcrumb
      li
        = link_to content_tag(:i, " " + t(".home"), class: "fa fa-home"), admin_root_path
      li.active
        = t(".orders")
  .row
    .col-lg-12
      .panel-heading
        .col-lg-3
          = t(".orders")
        = form_for :search, url: admin_orders_path, method: :get do |f|
          = render partial: "admin/orders/shared/search", locals: {f: f}
      br
      br
      .panel.panel-default
        .panel-body
          .table-responsive
            table.table.table-hover
              thead
                tr
                  th
                    = t(".user-name")
                  th
                    = t(".receiver")
                  th
                    = t(".address")
                  th
                    = t(".phone")
                  th
                    = t(".email")
                  th
                    = t(".date")
                  th
                    = t(".total-money")
                  th
                    | Loại thanh toán
                  th
                    = t(".status")
                  th
                    | Action
              tbody
                = render partial: "admin/orders/shared/listtable", collection: @orders, as: "list"
            = render "admin/orders/shared/modal"
          = will_paginate
= javascript_include_tag "include/lib/simple.money.format"