config/routes.rb
Rails.application.routes.draw do
  root to: 'public_pages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :sessions
  namespace :admin do
    root to: 'homes#index'
    resources :users
    resources :categories
    resources :products
    resources :orders
  end
  get '/auth/google_oauth2', as: 'google'
  get 'auth/:provider/callback', to: 'sessions#login_google'
  get 'auth/failure', to: redirect('/')
  resources :account_activations, only: [:edit]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token

  before_save { email.downcase! }
  before_create :create_activation_digest

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  PHONE_REGEX = /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/
  validates :email, presence: true,
                    length: { maximum: Settings.max_email_length },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  # validates :name,  presence: true, length: { maximum: 50 }
  # validates :phone, uniqueness: true, length: { maximum: 15 },
  #                   format: { with: PHONE_REGEX }, numericality: true

  has_secure_password

  validates :password,
            presence: true, allow_nil: true,
            length: { minimum: Settings.min_password_length }
  validates :password_confirmation,
            presence: true, allow_nil: true,
            length: { minimum: Settings.min_password_length }

  # Returns the hash digest of the given string.
  class << self
    def digest(string)
      if cost = ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.first_name + ' ' + auth.info.last_name
      user.email = auth.info.email
      user.password = SecureRandom.urlsafe_base64
      user.save!
    end
  end

  private

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationAdminController
  before_action :logged_in_user
  before_action :check_admin
  before_action :load_user_id, only: %i[edit destroy update]

  def index
    if params[:search].blank?
      @users = User.paginate(page: params[:page], per_page: 5)
    else
      @users = User.all
      search_status_active
      search_status_lock
      search_name
      @users = @users.paginate(page: params[:page], per_page: 5)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.activated = true
    @user.activated_at = Time.zone.now
    if @user.save
      if params[:user][:avatar].present?
        render :crop
      else
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { success: t('.create-success') }
          end
        end
      end
    else
      respond_to do |format|
        format.html do
          redirect_to admin_users_url,
                      flash: { danger: t('.create-error') }
        end
      end
    end
  end

  def edit; end

  def show; end

  def update
    if @user.update_attributes user_params
      if params[:user][:avatar].present?
        render :crop
      else
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { success: t('.update-success') }
          end
        end
      end
    else
      respond_to do |format|
        format.html do
          redirect_to admin_users_url,
                      flash: { danger: t('.update-error') }
        end
      end
    end
  end

  def destroy
    if @user.deleted?
      if @user.restore
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { success: 'Mở khóa thành công !' }
          end
        end
      else
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { success: 'Mở khóa thất bại !' }
          end
        end
      end
    else
      if @user.destroy
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { success: 'Khóa thành công !' }
          end
        end
      else
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { danger: 'Khóa thất bại !' }
          end
        end
      end
    end
  end

  def destroy_multiple
    if params[:deleted] == '0'
      if User.restore(params[:users])
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { success: 'Mở khóa thành công !' }
          end
        end
      else
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { danger: 'Mở khóa thất bại !' }
          end
        end
      end
    else
      if User.destroy(params[:users])
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { success: 'Khóa thành công !' }
          end
        end
      else
        respond_to do |format|
          format.html do
            redirect_to admin_users_url,
                        flash: { danger: 'Khóa thất bại !' }
          end
        end
      end
    end
  end

  private

    def load_user_id
      @user = User.with_deleted.find_by(id: params[:id])
      @user || render(file: 'public/404.html', status: 404, layout: true)
    end

    def user_params
      params.require(:user).permit!
    end

    def search_name
      @users = @users.search_name params[:search][:name] if params[:search][:name].present?
    end

    def search_status_active
      return unless params[:search][:status_active].present?
      status = params[:search][:status_active]
      @users =
        if status == 'notactive'
          @users.where(activated: nil)
        else
          @users.where(activated: true)
        end
    end

    def search_status_lock
      return unless params[:search][:status_lock].present?
      status = params[:search][:status_lock]
      @users =
        if status == 'lock'
          @users.only_deleted
        else
          @users.all
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to root_path
    else
      render :new
    end
  end

  private

    def find_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    current_user.role == 'admin'
  end

  def set_name
    if params[:search].present?
      params[:search][:name] if params[:search][:name].present?
    end
  end

  def set_status_active
    if params[:search].present?
      params[:search][:status_active] if params[:search][:status_active].present?
    end
  end

  def set_status_lock
    if params[:search].present?
      params[:search][:status_lock] if params[:search][:status_lock].present?
    end
  end
end

app/views/admin/users/shared/_form.html.slim
.control-group
  = f.label :role, t(".role"), { class: "control-label", for: "role" }
  = f.select :role,
  - options_for_select([[t(".member"), :member], [t(".admin"), :admin]],
    :selected => (f.object.admin? == true ? :admin : :member)), {}, { :id => "role", :class => "form-control" }
.control-group
  = f.label :name, t(".full-name"), { class: "control-label", for: "name" }
  = f.text_field :name, { id: "name", class: "form-control", placeholder: t(".add-full-name") }
.control-group
  = f.label :email, t(".email"), { class: "control-label", for: "email" }
  - if f.object.id?
    = f.email_field :email, { id: "email", class: "form-control", placeholder: t(".add-email"), disabled: true }
  - else
    = f.email_field :email, { id: "email", class: "form-control", placeholder: t(".add-email") }
.control-group
  = f.label :password, t(".password"), { class: "control-label", for: "password" }
  = f.password_field :password, { id: "password", class: "form-control", placeholder: t(".add-password") }
.control-group
  = f.label :password_confirmation, t(".password-confirm"), { class: "control-label", for: "password_confirmation" }
  = f.password_field :password_confirmation, { id: "password_confirmation", class: "form-control", placeholder: t(".password-confirm") }
.control-group
  = f.label :address, t(".address"), { class: "control-label", for: "advanced-placepicker" }
  = f.text_field :address, { id: "advanced-placepicker", class: "form-control", 'data-map-container-id': "collapseTwo", placeholder: t(".add-address") }
#collapseTwo.collapse
  .another-map-class.thumbnail
.control-group
  = f.label :phone, t(".phone"), { class: "control-label", for: "phone" }
  = f.text_field :phone, { id: "phone", class: "form-control", placeholder: t(".add-phone") }
.control-group
  = f.label :avatar, t(".avatar"), { class: "control-label", for: "avatar" }
  br
  - if f.object.avatar?
    = image_tag(f.object.avatar_url(:thumb), :id => "img", :class => "img-thumbnail", width: 150)
  - else
    = image_tag("", :class => "img img-add img-thumbnail")
  = f.file_field :avatar, accept: "image/jpeg,image/gif,image/png",  :id => "avatar", :class => "form-control"
br
= f.submit yield(:button_text), class: "btn btn-primary"

app/views/admin/users/shared/_listtable.html.slim
- unless (list == current_user && list.admin?)
  tr
    td
      .form-check
        label
          = check_box_tag "users[]", list.id, false, class: "checkbox"
          = content_tag(:span, nil, class: "label-text")
    td
      = list.name
    td
      = list.address
    td
      = list.phone
    td
      = list.email
    td
      = format_day list.created_at
    td
      = list.admin? ? content_tag(:span, t(".admin"), class: "label label-primary") : content_tag(:span, t(".member"), class: "label label-default")
    td
      = list.activated? ? content_tag(:span, t(".activated"), class: "label label-info") : content_tag(:span, t(".not-activated"), class: "label label-warning")
    td
      = link_to raw('<i class="fa fa-edit fa-1x"></i>'), edit_admin_user_path(list.id), class: "btn btn-warning", 'data-toggle-tooltip': 'tooltip', 'data-placement': 'left', 'title': 'Khóa tài khoản'
    td
      - if list.deleted?
        = link_to(content_tag(:i, nil, class: "fa fa-unlock fa-1x"), admin_user_path(list.id), class: "btn btn-danger", method: :delete, data: { confirm: t(".are-u-sure") }, 'data-toggle-tooltip': 'tooltip', 'data-placement': 'left', 'title': 'Mở tài khoản')
      - else
        = link_to(content_tag(:i, nil, class: "fa fa-lock fa-1x"), admin_user_path(list.id), class: "btn btn-danger", method: :delete, data: { confirm: t(".are-u-sure") }, 'data-toggle-tooltip': 'tooltip', 'data-placement': 'left', 'title': 'Khóa tài khoản')

app/views/admin/users/shared/_search.html.slim
.col-lg-9
  .col-lg-2.pull-right
    = f.submit "Tìm kiếm", class: "btn btn-primary"
  .col-lg-3.pull-right
    = f.select :status_active, options_for_select([["Chọn", nil], ["Chưa kích hoạt", :notactive], ["Đã kích hoạt", :active]], selected: set_status_active), {}, { id: "status_active", class: "form-control" }
  .col-lg-3.pull-right
    = f.select :status_lock, options_for_select([["Hoạt động", :unlock], ["Bị khóa", :lock]], selected: set_status_lock), {}, { id: "status_lock", class: "form-control" }
  .col-lg-3.pull-right
    = f.text_field :name, { id: "name", class: "form-control", placeholder: "Nhập tên tài khoản", value: set_name }